### ISSUE TITLE
请教一下batch size的问题

### ISSUE THREAD

**Issue by Feng1909** [Irvingao/paddle-inference-ros#2]
如果我在这里把max batchsize设置为2，[这里](https://github.com/Irvingao/paddle_inference_ros/blob/master/scripts/pp_infer.py#L66)，是否是指同时预测两张图呢，这个时候的输入应该怎么写呢，谢谢

**Comment by Irvingao** [comment]
您好，max-batchsize你的理解是正确的，其他应该是不需要调整的，你也可以参考paddle-tensorrt的Wiki查看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Irvingao/paddle_inference_ros] 请教一下batch size的问题 (#2)




 
如果我在这里把max batchsize设置为2，这里，是否是指同时预测两张图呢，这个时候的输入应该怎么写呢，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Feng1909** [comment]
好的，非常感谢！
